name: Main CI

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    environment: tests

    env:
      MAIN_URL: ${{ vars.MAIN_URL }}

    steps:
      - uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.2

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip

      - name: Install Poetry
        run: | 
          pip install poetry

      - name: Install project
        run: |
          poetry install --no-root

      - name: Install Pytest
        run: |
          poetry run pytest

      - name: Install Mypy
        run: |
          poetry run mypy ./

      - name: Install Pylint
        run: |
          poetry run pylint ./app
          
  build:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'
#    if: startsWith(github.ref, 'ref/tags/')

    needs: [run-tests]

    steps:
      - name: Login to Docker
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin

      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t ${{ vars.DOCKER_PROJECT }}:${GITHUB_REF_NAME} -f Dockerfile .

      - name: Push image to Dockerhub
        run: docker push ${{ vars.DOCKER_PROJECT }}:${GITHUB_REF_NAME}